### ISSUE TITLE
Database migration from 0.12.1 to 1.0.0-rc.1 errors

### ISSUE THREAD

**Issue by benwilson512** [sorentwo/oban#155]
### Environment

- Oban Version
Was 0.12.1, is now 1.0.0-rc.1

- PostgreSQL Version
```
psql (11.6)
Type "help" for help.

sensetra_dev=#     SELECT description
sensetra_dev-#     FROM pg_class
sensetra_dev-#     LEFT JOIN pg_description ON pg_description.objoid = pg_class.oid
sensetra_dev-#     LEFT JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
sensetra_dev-#     WHERE pg_class.relname = 'oban_jobs'
sensetra_dev-#     AND pg_namespace.nspname = 'public'
sensetra_dev-# ;
 description 
-------------
 7
```
- Elixir & Erlang/OTP Versions (`elixir --version`)
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```

### Current Behavior

```
defmodule Sensetra.Repo.Migrations.UpdateOban do
  use Ecto.Migration

  def up do
    Oban.Migrations.up()
  end
end
```
```
[info] == Running 20200122145734 Sensetra.Repo.Migrations.UpdateOban100Rc0.up/0 forward
[info] alter table public.oban_jobs
[info] Application sensetra exited: Sensetra.start(:normal, []) returned an error: shutdown: failed to start child: Sensetra.Repo.Migrator
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42703 (undefined_column) column "priority" of relation "oban_jobs" does not exist
            (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (ecto_sql) lib/ecto/adapters/sql.ex:716: Ecto.Adapters.SQL.execute_ddl/4
            (ecto_sql) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
            (ecto_sql) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
            (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
            (ecto_sql) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
            (stdlib) timer.erl:166: :timer.tc/1
```

**Comment by benwilson512** [comment]
Possibly the issue is here: https://github.com/sorentwo/oban/blob/master/lib/oban/migrations.ex#L411 Maybe you need to `flush()` the `add_if_not_exists` columns before attempting to modify them?

**Comment by sorentwo** [comment]
Thanks for the report and pardon the slow fix. I'll have rc.2 out shortly.

**Comment by benwilson512** [comment]
Fix was anything but slow, thanks!
