### ISSUE TITLE
Error on retrying discarded job

### ISSUE THREAD

**Issue by jaimeiniesta** [sorentwo/oban#171]
### Environment

      {:oban, "~> 1.0.0"}
      {:oban_web, "~> 1.1.0"}
      heroku
      Erlang/OTP 22
      Elixir 1.8.1
- Oban Version
- PostgreSQL Version
- Elixir & Erlang/OTP Versions (`elixir --version`)

### Current Behavior

When I click on the "Retry" button for a discarded job on the UI, I  see this on the logs:

```
2020-02-13T21:28:58.054374+00:00 app[web.1]: 21:28:58.054 [error] GenServer #PID<0.7854.0> terminating
2020-02-13T21:28:58.054384+00:00 app[web.1]: ** (ArgumentError) malformed update `[set: [state: "available"], log: false]` in query expression, expected a keyword list with set/push/pop as keys with field-value pairs as values
2020-02-13T21:28:58.054384+00:00 app[web.1]: (ecto) lib/ecto/query/builder/update.ex:187: Ecto.Query.Builder.Update.runtime_error!/1
2020-02-13T21:28:58.054418+00:00 app[web.1]: (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
2020-02-13T21:28:58.054419+00:00 app[web.1]: (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
2020-02-13T21:28:58.054420+00:00 app[web.1]: (ecto) lib/ecto/query/builder/update.ex:153: Ecto.Query.Builder.Update.update!/4
2020-02-13T21:28:58.054420+00:00 app[web.1]: (ecto) lib/ecto/repo/queryable.ex:132: Ecto.Repo.Queryable.update_all/4
2020-02-13T21:28:58.054421+00:00 app[web.1]: (oban_web) lib/oban_web/query.ex:39: ObanWeb.Query.deschedule_job/2
2020-02-13T21:28:58.054421+00:00 app[web.1]: (oban_web) lib/oban_web/live/dashboard_live.ex:200: ObanWeb.DashboardLive.deschedule_job/2
2020-02-13T21:28:58.054422+00:00 app[web.1]: (oban_web) lib/oban_web/live/dashboard_live.ex:101: ObanWeb.DashboardLive.handle_info/2
2020-02-13T21:28:58.054422+00:00 app[web.1]: Last message: {:deschedule_job, 2390756}
```
### Expected Behavior

The job should be retried.

### Possible causes

The job was moved from `discarded` to `available` with a query to update just the `state`, so it currently shows "attempts 12 of 10".

**Comment by sorentwo** [comment]
Please upgrade to v1.1.2, it is fixed there. I've noticed that `mix deps.update oban_web` doesn't always catch the patch version, so you may need to specify `oban_web, "~> 1.1.2"`.
