### ISSUE TITLE
Oban.Queue.*.Producer error

### ISSUE THREAD

**Issue by sescobb27** [sorentwo/oban#206]
Hi having some background issues in oban that were reported to sentry

## Environment

- Oban Version: `1.2.0`
- Elixir & Erlang/OTP Versions (`elixir --version`):
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 21)
```

### Current Behavior

```
Task Oban.Queue.BackfillStreamingStructureS3.Producer started from #PID<0.507.3> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:expected_element_start_tag, {:file, :file_name_unknown}, {:line, 1}, {:col, 2}} of type Tuple. This protocol is implemented for the following type(s): Storage.Adapters.FileSystem.Wildcard, Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, File.Stream, Map, GenEvent.Stream, Date.Range, MapSet, HashSet, Stream, Function, HashDict, IO.Stream, List, Range
    (elixir 1.10.2) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.10.2) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.10.2) lib/enum.ex:3383: Enum.map_intersperse/3
    (elixir 1.10.2) lib/enum.ex:1495: Enum.map_join/3
    (elixir 1.10.2) lib/exception.ex:579: Exception.format_stacktrace/1
    (elixir 1.10.2) lib/exception.ex:145: Exception.format/3
    (oban 1.2.0) lib/oban/query.ex:212: Oban.Query.retry_job/6
    (oban 1.2.0) lib/oban/queue/executor.ex:102: Oban.Queue.Executor.report_failure/6
Function: #Function<2.63682627/0 in Oban.Queue.Producer.handle_info/2>
    Args: []
```

### Expected Behavior

it should not crash

**Comment by sescobb27** [comment]
I think this is a similar erro, maybe some errors in the worker is crashing the producer?

```
GenServer Oban.Queue.BackfillStreamingStructureS3.Producer terminating
** (MatchError) no match of right hand side value: {nil, %{}}
    (oban 1.2.0) lib/oban/queue/producer.ex:122: Oban.Queue.Producer.handle_info/2
    (stdlib 3.12) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.1851555622.272629767.219417>, :process, #PID<0.28469.10>, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: {:expected_element_start_tag, {:file, :file_name_unknown}, {:line, 1}, {:col, 2}}}, [{Enumerable, :impl_for!, 1, [file: 'lib/enum.ex', line: 1]}, {Enumerable, :reduce, 3, [file: 'lib/enum.ex', line: 141]}, {Enum, :map_intersperse, 3, [file: 'lib/enum.ex', line: 3383]}, {Enum, :map_join, 3, [file: 'lib/enum.ex', line: 1495]}, {Exception, :format_stacktrace, 1, [file: 'lib/exception.ex', line: 579]}, {Exception, :format, 3, [file: 'lib/exception.ex', line: 145]}, {Oban.Query, :retry_job, 6, [file: 'lib/oban/query.ex', line: 212]}, {Oban.Queue.Executor, :report_failure, 6, [file: 'lib/oban/queue/executor.ex', line: 102]}]}}
State: %Oban.Queue.Producer.State{circuit: :enabled, conf: %Oban.Config{beats_maxage: 300, circuit_backoff: 30000, crontab: [], dispatch_cooldown: 5, name: Oban, node: "somenode", poll_interval: 1000, prefix: "public", prune: {:maxage, 31536000}, prune_interval: 60000, prune_limit: 5000, queues: [backfill_streaming_structure_s3: 5, backfill_streaming_structure_azure: 5], repo: Models.Repo, rescue_after: 60, rescue_interval: 60000, shutdown_grace_period: 15000, timezone: "Etc/UTC", verbose: false}, cooldown_ref: nil, dispatched_at: -576458015065, foreman: Oban.Queue.BackfillStreamingStructureS3.Foreman, limit: 5, name: Oban.Queue.BackfillStreamingStructureS3.Producer, nonce: "i04ekbl4", paused: false, poll_ref: #Reference<0.1851555622.273416196.206151>, queue: "backfill_streaming_structure_s3", rescue_ref: #Reference<0.1851555622.273154051.112915>, running: %{}, started_at: ~U[2020-04-01 21:11:47.898507Z]}
```

**Comment by sorentwo** [comment]
The producer crash is bubbling up after some retries from an error in recording the exception on the job.

Somehow this is coming from xmerl's strange error handling, (maybe via ex_aws and sweet_xml?). Anyhow, calls to parser functions in `xmerl` will exit with a reason like this:

```elixir
{:fatal, {:unexpected_end, {:file, :file_name_unknown}, {:line, 1}, {:col, 7}}}
```

In my tests and experimentation I can't get this to cause an exception formatting error. Is there any special error handling in your worker?

**Comment by sescobb27** [comment]
yes we are using sweetxml, and for those kind of errors we tried to do a catch as that was the suggested way, but nothing else

```
  defp safe_parse(body) do
    parse(body)
  catch
    :exit, _ -> {:error, :unable_to_parse_xml_body}
  end
```

**Comment by sorentwo** [comment]
The only way I can reproduce this is by explicitly passing a tuple as the stacktrace:

```elixir
iex(10)> Exception.format(:error, {:fatal, :expected_element_start_tag}, {:expected_element_start_tag, {:file, :file_name_unknown}, {:line, 1}, {:col, 2}})
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:expected_element_start_tag, {:file, :file_name_unknown}, {:line, 1}, {:col, 2}} of type Tuple
    (elixir 1.10.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.10.1) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.10.1) lib/enum.ex:3383: Enum.map_intersperse/3
    (elixir 1.10.1) lib/enum.ex:1495: Enum.map_join/3
    (elixir 1.10.1) lib/exception.ex:579: Exception.format_stacktrace/1
    (elixir 1.10.1) lib/exception.ex:145: Exception.format/3
```

I'm not sure how that would ever happen though. The stacktrace either comes from `__STACKTRACE__` or `Process.info(:current_stacktrace)`, both of which should always be a list.

**Comment by sescobb27** [comment]
ok, erlang messing around with elixir 🤔, so the exception is raised in that case, but that is killing the producer, it should only kill the worker, right? i will need to do a `catch` and also `rescue` in that scenario

**Comment by sescobb27** [comment]
hmmm maybe you can reproduce the error with this, that is throwing an exit in other part of the worker which wasn't being handled and that caused the producer to crash, also with that the job didn't update the error log

```elixir
SweetXml.parse ""
```

**Comment by sorentwo** [comment]
The fatal error is happening after the worker has ran and during the attempt to record the exception on the job in the database. That happens in the execution task and is something that _should_ crash the producer because it monitors the job.

I've attempted this with SweetXml and many different scenarios. I can't figure out what is generating that stacktrace. If you can reproduce this in an isolated setup I would love to provide a fix for it. As is currently, there doesn't seem to be anything I can do (or anything that oban is doing wrong).
