### ISSUE TITLE
Ecto.SubQueryError with Ecto 3.4.3

### ISSUE THREAD

**Issue by rockwood** [sorentwo/oban#224]
Hi, I upgraded Ecto to 3.4.3 and got the following error when starting my application. Downgrading to Ecto 3.4.2 fixes the issue. 

### Environment

- Oban Version: 1.2
- PostgreSQL Version: 12.2
- Postgrex Version: 0.15.3
- Ecto Version: 3.4.3
- Elixir & Erlang/OTP Versions: 1.10.2 OTP 21

### Current Behavior

```elixir
[error] GenServer Oban.Queue.Default.Producer terminating
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Ecto.Query.Planner.plan_wheres/2

The subquery originated from the following query:

from j0 in Oban.Job,
  join: j1 in subquery(from j0 in Oban.Job,
  left_join: b1 in Oban.Beat,
  on: j0.attempted_by == [b1.node, b1.queue, b1.nonce] and b1.inserted_at > ^~U[2020-05-07 00:52:18.669349Z],
  where: j0.state == "executing" and j0.queue == ^"default",
  where: is_nil(b1.node),
  select: [:id]),
  on: j0.id == j1.id,
  where: j0.attempt < j0.max_attempts,
  update: [set: [state: ^"available"]]

    (ecto 3.4.3) lib/ecto/repo/queryable.ex:176: Ecto.Repo.Queryable.execute/4
    (oban 1.2.0) lib/oban/query.ex:113: Oban.Query.rescue_orphaned_jobs/2
    (oban 1.2.0) lib/oban/queue/producer.ex:218: Oban.Queue.Producer.rescue_orphans/1
    (oban 1.2.0) lib/oban/queue/producer.ex:89: Oban.Queue.Producer.handle_continue/2
    (stdlib 3.11) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.11) gen_server.erl:388: :gen_server.loop/7
    (stdlib 3.11) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
State: %Oban.Queue.Producer.State{circuit: :enabled, conf: %Oban.Config{beats_maxage: 300, circuit_backoff: 30000, crontab: [{%Oban.Crontab.Cron{days: [:*], hours: [2], minutes: [0], months: [:*], weekdays: [:*]}, Pebble.Members.DeliverCampaignsWorker, []}, {%Oban.Crontab.Cron{days: [:*], hours: [:*], minutes: [0], months: [:*], weekdays: [:*]}, Pebble.Members.ReconcileShopsWorker, []}], dispatch_cooldown: 5, name: Oban, node: "RockMac", poll_interval: 1000, prefix: "public", prune: {:maxlen, 1000}, prune_interval: 60000, prune_limit: 5000, queues: [default: 10], repo: Pebble.Repo, rescue_after: 60, rescue_interval: 60000, shutdown_grace_period: 15000, timezone: "Etc/UTC", verbose: false}, cooldown_ref: nil, dispatched_at: nil, foreman: Oban.Queue.Default.Foreman, limit: 10, name: Oban.Queue.Default.Producer, nonce: "05lq9tce", paused: false, poll_ref: nil, queue: "default", rescue_ref: nil, running: %{}, started_at: ~U[2020-05-07 00:53:18.669309Z]}
[info] Application  xxx exited: shutdown
```

**Comment by sorentwo** [comment]
That is a transient error from compiled Ecto code. I ran into the same thing for all queries after an upgrade. Deleting your _build folder and recompiling will fix the issue.

**Comment by rockwood** [comment]
@sorentwo Got it. Thanks for the help!
