### ISSUE TITLE
Ecto.SubQueryError with ecto_sql 3.4.4 on app start

### ISSUE THREAD

**Issue by azizk** [sorentwo/oban#251]
### Environment

- Oban Version: 1.2
- PostgreSQL Version: 11.6
- Elixir & Erlang/OTP Versions:
> Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
> Elixir 1.10.1 (compiled with Erlang/OTP 22)

### Current Behavior

When I upgrade from ecto_sql 3.4.1 to 3.4.4, then compile and start the app I get a stream of errors (the same for each queue) until it shuts down:

```
...*snip*...

[error] GenServer Oban.Queue.Emails.Producer terminating
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Ecto.Query.Planner.plan_wheres/2

The subquery originated from the following query:

from j0 in Oban.Job,
  join: j1 in subquery(from j0 in Oban.Job,
  left_join: b1 in Oban.Beat,
  on: j0.attempted_by == [b1.node, b1.queue, b1.nonce] and b1.inserted_at > ^~U[2020-05-29 12:13:15.987830Z],
  where: j0.state == "executing" and j0.queue == ^"emails",
  where: is_nil(b1.node),
  select: [:id]),
  on: j0.id == j1.id,
  where: j0.attempt < j0.max_attempts,
  update: [set: [state: ^"available"]]

    (ecto 3.4.4) lib/ecto/repo/queryable.ex:176: Ecto.Repo.Queryable.execute/4
    (oban 1.2.0) lib/oban/query.ex:113: Oban.Query.rescue_orphaned_jobs/2
    (oban 1.2.0) lib/oban/queue/producer.ex:218: Oban.Queue.Producer.rescue_orphans/1
    (oban 1.2.0) lib/oban/queue/producer.ex:89: Oban.Queue.Producer.handle_continue/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:388: :gen_server.loop/7
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
State: %Oban.Queue.Producer.State{circuit: :enabled, conf: %Oban.Config{beats_maxage: 300, circuit_backoff: 30000, crontab: [], dispatch_cooldown: 5, name: Oban, node: "aziz-srvr", poll_interval: 1000, prefix: "public", prune: {:maxlen, 100000}, prune_interval: 60000, prune_limit: 5000, queues: [events: 100, ofiles: 30, assets: 10, videos: 1, emails: 20], repo: MyApp.Repo, rescue_after: 60, rescue_interval: 60000, shutdown_grace_period: 15000, timezone: "Etc/UTC", verbose: false}, cooldown_ref: nil, dispatched_at: nil, foreman: Oban.Queue.Emails.Foreman, limit: 20, name: Oban.Queue.Emails.Producer, nonce: "ibrhvu43", paused: false, poll_ref: nil, queue: "emails", rescue_ref: nil, running: %{}, started_at: ~U[2020-05-29 12:14:15.986382Z]}

...*snip*...

[info] Application my_app exited: shutdown
** (Mix) Could not start application my_app_web: {:not_running, :my_app}
```

### Expected Behavior

Should work just fine with ecto_sql 3.4.4

**Comment by sorentwo** [comment]
I saw this too when I upgraded initially. Clearing the `_build` directory and recompiling fixed the issue. It isn't specifically a problem with Oban, but it looks that way because the first query that your app is executing is from a queue producer on startup.
