### ISSUE TITLE
Executor runtime exception upon start

### ISSUE THREAD

**Issue by MainShayne233** [sorentwo/oban#270]
### Environment

- Oban Version: `2.0.0-rc.1`
- PostgreSQL Version: `12.3`
- Elixir & Erlang/OTP Versions:
```
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```

### Current Behavior

I set up my app via README instructions, and upon starting the app with the `crontab` enabled, I get:

```elixir
[error] Task Oban.Queue.Events.Producer started from #PID<0.524.0> terminating
** (KeyError) key :reason not found
    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1
    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Oban.Queue.Executor.call/1
    Args: [%Oban.Queue.Executor{conf: %Oban.Config{circuit_backoff: 30000, crontab: [], dispatch_cooldown: 5, log: false, name: Oban, node: "localhost", plugins: [], poll_interval: 1000, prefix: "public", queues: [default: 10, events: 50], repo: Scrape.Repo, shutdown_grace_period: 15000, timezone: "Etc/UTC"}, duration: 0, error: nil, job: %Oban.Job{__meta__: #Ecto.Schema.Metadata<:loaded, "public", "oban_jobs">, args: %{"id" => "HI"}, attempt: 8, attempted_at: ~U[2020-06-16 20:44:27.570154Z], attempted_by: ["localhost", "events", "799qp6do"], completed_at: nil, discarded_at: nil, errors: [%{"at" => "2020-06-16T20:26:49.204425Z", "attempt" => 1, "error" => "** (KeyError) key :reason not found\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1\n    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}, %{"at" => "2020-06-16T20:38:44.236674Z", "attempt" => 2, "error" => "** (KeyError) key :reason not found\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1\n    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}, %{"at" => "2020-06-16T20:39:03.490702Z", "attempt" => 3, "error" => "** (KeyError) key :reason not found\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1\n    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}, %{"at" => "2020-06-16T20:39:26.496256Z", "attempt" => 4, "error" => "** (KeyError) key :reason not found\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1\n    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}, %{"at" => "2020-06-16T20:39:57.534816Z", "attempt" => 5, "error" => "** (KeyError) key :reason not found\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1\n    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}, %{"at" => "2020-06-16T20:40:44.579272Z", "attempt" => 6, "error" => "** (KeyError) key :reason not found\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1\n    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}, %{"at" => "2020-06-16T20:42:03.666900Z", "attempt" => 7, "error" => "** (KeyError) key :reason not found\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:85: Oban.Queue.Executor.resolve_worker/1\n    (oban 2.0.0-rc.1) lib/oban/queue/executor.ex:68: Oban.Queue.Executor.call/1\n    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3\n"}], id: 1, inserted_at: ~U[2020-06-15 22:48:25.976006Z], max_attempts: 20, priority: 0, queue: "events", scheduled_at: ~U[2020-06-16 20:44:26.666838Z], state: "executing", tags: [], unique: nil, unsaved_error: nil, worker: "Scrape.Worker"}, kind: nil, meta: %{args: %{"id" => "HI"}, attempt: 8, id: 1, max_attempts: 20, prefix: "public", queue: "events", worker: "Scrape.Worker"}, queue_time: 0, safe: true, snooze: nil, stacktrace: [], start_mono: -576460702283963515, start_time: 1592340267597744392, state: :unset, stop_mono: nil, worker: nil}]
```

Dug a bit, and found: https://github.com/sorentwo/oban/blob/master/lib/oban/queue/executor.ex#L85

`:reason` doesn't seem to be a field defined on the module struct, but it's trying to get set here.

### Expected Behavior

I'd expect to not see the error.

**Comment by MainShayne233** [comment]
And a note: I downgraded `oban` to `1.2` and only changed my worker's `perform` function to be of arity 2 and it works fine. :-)

**Comment by sorentwo** [comment]
Thanks for the report. Dialyzer was of absolutely no help here!

**Comment by MainShayne233** [comment]
Aw, poor dialyzer.

You could get a compile error to raises in cases like this by using the struct update syntax: `%StructName{struct | key: val}`
