### ISSUE TITLE
Error on inserting job

### ISSUE THREAD

**Issue by Mdsp9070** [sorentwo/oban#396]
### Environment

- Oban Version: {:oban, "~> 2.3"}
- PostgreSQL Version: PostgreSQL 13.0
- Elixir & Erlang/OTP Versions (`elixir --version`):
```sh
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.11.0 (compiled with Erlang/OTP 23)
```

### Current Behavior

I cannot use `Oban.insert/2`, it gives me this error:
```sh
** (MatchError) no match of right hand side value: []
    (oban 2.3.4) lib/oban/registry.ex:16: Oban.Registry.config/1
    (oban 2.3.4) lib/oban.ex:236: Oban.insert/2
```

### Expected Behavior

Inserts job without errors.

### Information

one of my emails jobs:
```elixir
defmodule Bank.Accounts.Jobs.RecoveryEmail do
  @moduledoc """
  Sends an email to user that forgot their password
  """
  use Bank.Jobs.Worker, queue: :mailing

  import Bank.Common.Wrapping

  alias Bank.{Accounts, Repo}
  alias Bank.Mailing

  def perform(%{"token" => token}) do
    %{user: user} =
      token
      |> Accounts.get_password_recovery()
      |> ok_unwrap()
      |> Repo.preload(:user)

    %{
      subject: "Recuperação de conta",
      template: "password_recovery",
      assigns: %{token: token},
      to_email: user.email
    }
    |> Mailing.send_single_mail()
  end

  def create_worker(%{token: token}) do
    %{token: token}
    |> __MODULE__.new()
    |> Oban.insert()
  end
end
```

job worker:
```elixir
defmodule Bank.Jobs.Worker do
  @moduledoc """
  Extension of Oban.Worker
  """

  defmacro __using__(opts \\ []) do
    quote do
      use Oban.Worker, unquote(opts)
      import Bank.Common.Wrapping

      def create_generic_worker(resource) do
        %{id: resource.id}
        |> __MODULE__.new()
        |> Oban.insert()
      end
    end
  end
end
```

function on controller:
```elixir
  @accepts ~w(email)a
  def create_recovery(_conn, params) do
    with {:ok, user} <- Accounts.get_user_by(email: params["email"]),
         {:ok, recovery} <- Accounts.create_password_recovery(user) do
      recovery
      |> RecoveryEmail.create_worker()

      create_response(%{message: :recovery_attempt_created})
    else
      {:error, :not_found} ->
        {:error, :not_found}

      {:error, changeset} ->
        changeset
        |> Changeset.default_error_response()
    end
  end
```

**Comment by sorentwo** [comment]
Have you been able to insert jobs in the past? Did this just start happening?

Please show your Oban configuration, I have a hunch it is configured to use an alternate name.

**Comment by Mdsp9070** [comment]
No, I created the modules and wrote tests, and they're failing with this error

```elixir
# Oban
# Configures Oban
config :bank, Oban,
  repo: Bank.Repo,
  prune: {:maxlen, 10_000},
  queues: [default: 10, events: 50, media: 20, mailing: 50]
```

**Comment by sorentwo** [comment]
That would do it. The `prune` config is outdated for Oban 2.3, you need to use `plugins` instead. As is the Oban supervisor is crashing due to invalid configuration, you should see something in your logs.

Try this configuration instead:

```elixir
# config.exs

config :bank, Oban,
  repo: Bank.Repo,
  queues: [default: 10, events: 50, media: 20, mailing: 50],
  plugins: [{Oban.Plugins.Pruner, max_age: 300}]
  
# test.exs

config :bank, Oban, crontab: false, queues: false, plugins: false
```

The basic pruner plugin supports `max_age` and not `max_len`, so here I've set it to 5 minutes.

**Comment by Mdsp9070** [comment]
Actually, no difference...
```
6) test users POST /users with valid data creates an user (BankWeb.UserControllerTest)
     test/bank_web/controllers/user_controller_test.exs:85
     ** (MatchError) no match of right hand side value: []
     code: post(ctx.conn, "/api/v1/users", @valid_attrs)
     stacktrace:
       (oban 2.3.4) lib/oban/registry.ex:16: Oban.Registry.config/1
       (oban 2.3.4) lib/oban.ex:236: Oban.insert/2
       (bank 0.1.0) lib/bank_web/controllers/user_controller.ex:25: BankWeb.UserController.create/2
       (bank 0.1.0) lib/bank_web/controllers/user_controller.ex:1: BankWeb.UserController.action/2
       (bank 0.1.0) lib/bank_web/controllers/user_controller.ex:1: BankWeb.UserController.phoenix_controller_pipeline/2
       (phoenix 1.5.7) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
       (bank 0.1.0) lib/bank_web/endpoint.ex:1: BankWeb.Endpoint.plug_builder_call/2
       (bank 0.1.0) lib/bank_web/endpoint.ex:1: BankWeb.Endpoint.call/2
       (phoenix 1.5.7) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/bank_web/controllers/user_controller_test.exs:87: (test)
```

Here's my test:
```
    test "POST /users with valid data creates an user", ctx do
      conn =
        post(ctx.conn, "/api/v1/users", @valid_attrs)
        |> doc(
          "Creates a new account",
          on_nil: [
            email: :error,
            first_name: :error,
            last_name: :error,
            cpf: :error,
            cnpj: :error,
            mobile: :error,
            password: :error,
            password_confirmation: :error,
            new_password: :error,
            new_password_confirmation: :error
          ]
        )

      %{conn | body_params: conn.body_params |> Map.delete("confirmed?"), resp_headers: %{}}

      %{"message" => message, "data" => user} = conn |> Map.get(:resp_body) |> Jason.decode!()

      ConfirmationEmail.perform(%{"id" => user["id"]})

      assert conn.status == 201
      assert message == "created"

      assert user["first_name"] == @valid_attrs.first_name
      assert user["last_name"] == @valid_attrs.last_name
      assert user["cnpj"] == @valid_attrs.cnpj
      assert user["email"] == @valid_attrs.email

      complete_user = user["id"] |> Accounts.get_user!()

      # Ensure a password was set
      refute nil == complete_user.password_hash
      refute complete_user.confirmed?

      assert_enqueued(worker: ConfirmationEmail, args: %{id: user["id"]})
      assert_email_delivered_with(to: [nil: user["email"]])
    end
```

**Comment by sorentwo** [comment]
Are you starting the Oban supervisor in your application? I’d you didn’t get an error message before either it seems like Oban isn’t started.

**Comment by Mdsp9070** [comment]
Indeed, I was starting the wrong way!
