### ISSUE TITLE
DBConnection.OwnershipError with crontab: false

### ISSUE THREAD

**Issue by romaluca** [sorentwo/oban#431]
Hi i have in my `config.exs` this:
```
config :shuttertop, Oban,
  repo: Shuttertop.Repo,
  plugins: [Oban.Plugins.Pruner],
  queues: [mails: 10, background: 10, media: 20],
  crontab: [
    {"*/15 * * * *", Shuttertop.Jobs.CheckContestsJob},
    {"0 0 * * *", Shuttertop.Jobs.CleanDevicesJob}
  ]
```
And in my test.exs this:
```
config :shuttertop, Oban,
  queues: false,
  plugins: false,
  crontab: false
```
if i launch `mix test`, it raise this error:
```
08:01:44.852 [error] GenServer {Oban.Registry, {Oban, {:plugin, Oban.Plugins.Cron}}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.1509.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection 2.3.1) lib/db_connection.ex:852: DBConnection.transaction/3
    (oban 2.4.3) lib/oban/plugins/cron.ex:119: anonymous fn/2 in Oban.Plugins.Cron.handle_info/2
    (telemetry 0.4.2) /home/luca/dev/shuttertop-elixir/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3
    (oban 2.4.3) lib/oban/plugins/cron.ex:118: Oban.Plugins.Cron.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:431: :gen_server.loop/7
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
If i remove the crontab part from config.exs, `mix test` works.
How can i do to disable crontab in test mode?
Thanks

**Comment by sorentwo** [comment]
The top level `crontab` setting is supported for backward compatibility. As described in the [overhauled cron](https://hexdocs.pm/oban/changelog.html#overhauled-cron) announcement from v2.4.0, you can move it into the plugins:

```elixir
config :shuttertop, Oban,
  repo: Shuttertop.Repo,
  queues: [mails: 10, background: 10, media: 20],
  plugins: [
    Oban.Plugins.Pruner,
    {Oban.Plugins.Cron,
     crontab: [
       {"*/15 * * * *", Shuttertop.Jobs.CheckContestsJob},
       {"0 0 * * *", Shuttertop.Jobs.CleanDevicesJob}
     ]}
  ]
```

Then remove the `crontab: false` line from your `test.exs`:

```diff
config :shuttertop, Oban,
    queues: false,
+- plugins: false
-  crontab: false
```
