### ISSUE TITLE
Workflow worker queries are logged even with "log: false"

### ISSUE THREAD

**Issue by crbelaus** [sorentwo/oban#492]
### Environment

- Oban Version: 2.6.1
- PostgreSQL Version: 13
- Elixir & Erlang/OTP Versions: Erlang/OTP 23 and Elixir 1.11.1

### Current Behavior

I have disabled Oban logs in my development configuration:

```elixir
config :my_app, Oban, log: false
```

I am using multiple workflow workers which log the following queries:

```
08:25:36.782 [debug] QUERY OK source="oban_producers" db=2.2ms
UPDATE "public"."oban_producers" AS o0 SET "running_ids" = array_remove(o0."running_ids", $1) WHERE (o0."uuid" = $2) [12240657, <<38, 4, 209, 233, 54, 83, 66, 15, 169, 85, 215, 253, 122, 195, 178, 41>>]
```

```
08:25:55.628 [debug] QUERY OK source="oban_jobs" db=1.7ms
UPDATE "public"."oban_jobs" AS o0 SET "state" = $1, "scheduled_at" = $2, "errors" = array_append(o0."errors", $3) WHERE (o0."id" = $4) ["retryable", ~U[2021-05-27 10:42:21.624229Z], %{at: ~U[2021-05-27 06:25:55.624285Z], attempt: 14, error: "** (BadMapError) expected a map, got: nil\n    :erlang.map_get(:value, nil)\n    (hcmex 0.40.0) lib/hcmex/workflows/event/on_date.ex:56: anonymous fn/3 in Hcmex.Workflows.Event.OnDate.eligible_workflows/1\n    (elixir 1.11.1) lib/enum.ex:3369: Enum.filter_list/2\n    (hcmex 0.40.0) lib/hcmex/workflows/event.ex:55: Hcmex.Workflows.Event.perform/1\n    (oban 2.6.1) lib/oban/queue/executor.ex:171: Oban.Queue.Executor.perform_inline/1\n    (oban 2.6.1) lib/oban/queue/executor.ex:159: Oban.Queue.Executor.perform_inline/1\n    (oban 2.6.1) lib/oban/queue/executor.ex:82: Oban.Queue.Executor.call/1\n    (elixir 1.11.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2\n    (elixir 1.11.1) lib/task/supervised.ex:35: Task.Supervised.reply/5\n    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3\n"}, 12261074]
```

This is not happening with normal workers, only with workflow workers.

### Expected Behavior

Workflow workers don't log this kind of queries as I explicitly disabled logging in my configuration.

**Comment by sorentwo** [comment]
@crbelaus Thanks for the report! This is fixed for the next patch release.
