### ISSUE TITLE
Running V10 Migration crashes due to null values in priority column

### ISSUE THREAD

**Issue by kaikuchn** [sorentwo/oban#502]
### Environment

- Oban Version: 2.7.2
- PostgreSQL Version: 12.7
- Elixir & Erlang/OTP Versions (`elixir --version`)
```
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.1 (compiled with Erlang/OTP 23)
```

### Current Behavior

`mix ecto.migrate` crashes with

```

17:20:27.272 [info]  == Running 20210615000000 Arbeitsentgelt.Repo.Migrations.UpgradeObanJobsToV10.up/0 forward

17:20:27.285 [debug] QUERY OK db=2.6ms
SELECT description
FROM pg_class
LEFT JOIN pg_description ON pg_description.objoid = pg_class.oid
LEFT JOIN pg_namespace ON pg_namespace.oid = pg_class.relnamespace
WHERE pg_class.relname = 'oban_jobs'
AND pg_namespace.nspname = 'public'
 []

17:20:27.290 [info]  alter table public.oban_jobs
** (Postgrex.Error) ERROR 23502 (not_null_violation) column "priority" contains null values

    table: oban_jobs
    column: priority
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.11.1) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:848: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
```

### Expected Behavior

Migration is successful even though `NULL` values exist.

**Comment by sorentwo** [comment]
The `priority` constraint added by V10 purposefully prevents `NULL` values. It isn't practical for Oban to run an `update` query because there's no way to know how many thousands/millions of jobs are in a table, and it could lock your jobs. In this case, you can unblock the migration by running this execute query in your migration (or beforehand):

```elixir
execute("UPDATE oban_jobs SET priority = 0 WHERE priority IS NULL")
```

The priority column has always had a default of 0. My guess is that you have some insert calls that were explicitly (mistakenly) inserting a `NULL` priority.
