### ISSUE TITLE
Oban Web: LiveView keeps crashing on pages of already pruned jobs

### ISSUE THREAD

**Issue by michallepicki** [sorentwo/oban#518]
### Environment

- Oban Version: `2.7.2`
- Elixir & Erlang/OTP Versions (`elixir --version`):
```
$ elixir --version
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

### Current Behavior

When viewing a detail page for old, already pruned jobs, because you're opening it anew (and I think also when you had it open while the job was being pruned), the page renders with placeholder data:
![image](https://user-images.githubusercontent.com/4972756/125624166-b39b8f35-0792-4707-8185-177db792fccb.png)

But the LiveView keeps crashing every ~2 seconds or so with:
```
14:23:59.415 [error] GenServer #PID<0.3152.0> terminating
** (KeyError) key :state not found in: %{}
    (oban_web 2.7.1) lib/oban/web/components/header_component.ex:24: Oban.Web.HeaderComponent.update/2
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/utils.ex:400: Phoenix.LiveView.Utils.maybe_call_update!/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:528: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib 3.15.1) maps.erl:410: :maps.fold_1/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:502: Phoenix.LiveView.Diff.render_pending_components/6
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/diff.ex:132: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:723: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.15.7) lib/phoenix_live_view/channel.ex:596: Phoenix.LiveView.Channel.handle_changed/4
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :refresh
```

### Expected Behavior

The LiveView should not keep crashing, and maybe it would be good for the user to see something like a "404" message instead of the placeholder data.

**Comment by sorentwo** [comment]
The error comes from empty params on `mount`, not because the job was deleted. This is fixed on main, but not yet released.

Thanks for the report 💛
