### ISSUE TITLE
Oban Producer terminated: new row for relation "oban_jobs" violates check constraint "attempt_range"

### ISSUE THREAD

**Issue by dsdshcym** [sorentwo/oban#532]
### Precheck

- Do a quick search and make sure the bug has not yet been reported
- For support, favor using the Elixir Forum, Slack, IRC, etc.
- Be friendly and polite!

### Environment

- Oban Version
  + oban 2.7.1
  + oban_pro 0.8.1
- PostgreSQL Version
  12.5
- Elixir & Erlang/OTP Versions (`elixir --version`)
  elixir:1.11.3-alpine

### Current Behavior

1. Our Oban queue stopped processing jobs
2. Oban.Producer was terminated due to this error:
    ```
    GenServer {Oban.Registry, {Oban, {:producer, "backfill"}}} terminating
    ** (Postgrex.Error) ERROR 23514 (check_violation) new row for relation "oban_jobs" violates check constraint "attempt_range"

        table: oban_jobs
        constraint: attempt_range
    ```
3. Oban.Producer was dispatching this job, and trying to increase its attempt to 4 (which is larger than its max_attempts 3)
   ```elixir
   %Oban.Job{
     __meta__: #Ecto.Schema.Metadata<:loaded, "oban_jobs">,
     args: %{...},
     attempt: 3,
     attempted_at: ~U[2021-08-08 05:14:16.968988Z],
     attempted_by: ["...node_id...", "24f37913-3196-48a3-89d5-63e39cb9bc71"],
     cancelled_at: nil,
     completed_at: nil,
     conf: nil,
     conflict?: false,
     discarded_at: ~U[2021-08-08 13:04:19.229770Z],
     errors: [
     %{
       "at" => "2021-08-05T20:59:32.895416Z",
       "attempt" => 1,
       "error" => "..."
     },
     %{
       "at" => "2021-08-08T13:04:19.229777Z",
       "attempt" => 3,
       "error" => "..."
     },
     %{
       "at" => "2021-08-08T13:04:27.429806Z",
       "attempt" => 2,
       "error" => "..."
     }
     ],
     id: 883,
     inserted_at: ~U[2021-08-03 01:00:00.654736Z],
     max_attempts: 3,
     meta: %{},
     priority: 0,
     queue: "backfill",
     replace: nil,
     scheduled_at: ~U[2021-08-08 13:04:46.429755Z],
     state: "available",
     tags: [],
     unique: nil,
     unsaved_error: nil,
     worker: "..."
   }
   ```
   which led to the constraint exception raised above
   
Note that 
1. the state was `"available"`, which was why Producer attempted to dispatch this job
1. the errors field was pretty interesting:
    1. attempt 3 was pushed into at 2021-08-08T13:04:19.229777Z
    2. attempt 2 was pushed into at 2021-08-08T13:04:27.429806Z (which was later than attempt 3)
    
Other contexts:
1. We are using `SmartEngine` with a global_limit option for this queue, 
   and we are running 2 elixir instances at the same time

   But I can't find the Producer db record with uuid `"24f37913-3196-48a3-89d5-63e39cb9bc71"` now

2. We are also using `LifeLine` plugin to bring jobs back to available state
3. We use default timers (30s for refresh, 1min for Stager)

I suspect there's some race condition here so 2 of our app instances got this job at the same time, and caused attempt 2 failed after attempt 3 (and that job's state changed from `discarded` to `retryable`)
But I couldn't find where this race condition happened

### Expected Behavior

1. Oban.Producer can somehow continue dispatch jobs even when `attempt_range` constraint was violated
   (Not sure if it's desirable or not)
2. No more jobs with `state="available"` and `attempt=max_attempts` in the future

**Comment by dsdshcym** [comment]
Hi @sorentwo!

Our app ran into this issue again today.
This time, I think I've found the cause:
1. We are using ex_aws inside our Oban jobs
   and ExAws is using a GenServer with ets to cache the auth token
   then somehow this `ExAws.Config.AuthCache` process crashed due to an error raised from https://github.com/ex-aws/ex_aws/blob/master/lib/ex_aws/instance_meta.ex#L26-L42
2. then `SmartEngine.format_blamed/1` failed to format this exception:
   ```
   Task #PID<0.16268.480> started from #PID<0.2221.0> terminating
   ** (Protocol.UndefinedError) protocol Enumerable not implemented for {GenServer, :call, [ExAws.Config.AuthCache, {:refresh_auth ...
      (elixir 1.11.3) lib/enum.ex:1: Enumerable.impl_for!/1
      (elixir 1.11.3) lib/enum.ex:141: Enumerable.reduce/3
      (elixir 1.11.3) lib/enum.ex:3473: Enum.map_intersperse/3
      (elixir 1.11.3) lib/enum.ex:1508: Enum.map_join/3
      (elixir 1.11.3) lib/exception.ex:576: Exception.format_stacktrace/1
      (elixir 1.11.3) lib/exception.ex:147: Exception.format/3
      (oban_pro 0.8.1) lib/oban/pro/queue/smart_engine.ex:216: Oban.Pro.Queue.SmartEngine.error_job/3
      (oban 2.7.1) lib/oban/queue/executor.ex:145: Oban.Queue.Executor.ack_event/1
   Function: #Function<1.16784814/0 in Oban.Queue.Producer.handle_info/2>
      Args: []
   ```
   (note that [BasicEngine](https://github.com/sorentwo/oban/blob/f4f75a2e9af5e400e36d718fc4b6c4b822ab05d7/lib/oban/queue/basic_engine.ex#L122) would fail in this case as well)
3. due to this exception, the job's state wasn't updated to `discarded` (when `job.attempt=job.max_attempts`)
   (because this [`Repo.update_all`](https://github.com/sorentwo/oban/blob/f4f75a2e9af5e400e36d718fc4b6c4b822ab05d7/lib/oban/queue/basic_engine.ex#L125) couldn't get called, same for SmartEngine)
4. then the Producer process received a `:DOWN` message from the Executor (is it correct?)
   but somehow this Producer couldn't find the executor ref in its `state.running` map:
   ```
   GenServer {Oban.Registry, {Oban, {:producer, "backfill"}}} terminating
   ** (MatchError) no match of right hand side value: nil
       (oban 2.7.1) lib/oban/queue/producer.ex:92: Oban.Queue.Producer.handle_info/2
       (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
       (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
       (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
   Last message: {:DOWN, #Reference<0.1427725466.1934098439.59919>, :process, #PID<0.16268.480>, {%Protocol.UndefinedError{description: "", protocol: Enumerable, value: {GenServer, :call, [ExAws.Config.AuthCache, {:refresh_auth, ...
   State: ...
   ```
   so the Producer process also crashed
5. since the Producer process crashed, it wouldn't refresh the Producer db record used by the SmartEngine
   1. Oban started a new Producer process with a new Producer db record
   2. Lifeline Plugin would bring that job back to "available" state (but the `job.attempt` was still equal to `job.max_attempts`)
6. when the new Producer spawned in 5.1 trying to execute the available job in 5.2, it would try to increase its `job.attempt`, led to the exception I noted in the issue description

I have 2 remaining questions:
1. Why would `ExAws.Config.AuthCache` failed to refresh the token?
2. Why would `Exception.format` got a `{GenServer, :call, ...}` as its stacktrace input argument, and triggered the exception?
3. Why couldn't the Producer process find the Executor (?) process's ref inside its `state.running` map
4. What can Oban do to ensure `Repo.update` gets called eventually?

I'm investigating 1 and 2, and I'll leave 3 and 4 to you.
Thank you for your time in advance!

**Comment by sorentwo** [comment]
@dsdshcym Thanks for the extremely thorough breakdown. That'll really help me get to the bottom of this.

**Comment by sorentwo** [comment]
@dsdshcym I have a couple of other questions to narrow down the issue:

1. Are you using `retry_exhausted` for the `Lifeline` plugin?
2. How many nodes are you running for the cluster and do you do rolling deploys?
3. Are you using a `timeout` for the worker that's erroring?

**Comment by dsdshcym** [comment]
1. Yes, we are using `retry_exausted: true` option. (But I don't think it's causing the bug, as the Lifeline plugin would increase the `max_attempts` counter)
2. We were running 2 nodes (k8s pods) when the bug happened. And we are using a kind of rolling deploy (terminate a pod, and start a new pod with the new image). But we didn't deploy any new versions when the bug happened. The bug happened several days after we deploy. 
3. No, we are not using any timeout option. (So jobs would run infinitely iirc)

(BTW, please expect a slower response from me recently. 🍼)

**Comment by dsdshcym** [comment]
Hi @sorentwo!

I now have a minimum reproducible setup for this issue!
https://github.com/dsdshcym/oban_format_error

I think there are 2 reasons that led to this issue:
1. Producer crashed (we may need a more stable Producer)
2. When Producer crashed, foreman (Task.Supervisor) process was still running (i.e. the jobs were still running)
   So this means that **the same job can be run twice at the same time** (with Lifeline + jobs that take quite some time)

   For example, let's say we have a Worker with max_attempts=3.
   And attempt 2 and attempt 3 are running at the same time (due to Producer crashes)
   But attempt 3 failed first, attempt 2 failed later.
   1. When attempt 3 failed, it would set job.state to discarded
      (because its job.attempt >= max_attempts)
   2. But when attempt 2 failed **later**, it would set job.state from discarded back to retryable
      (because SmartEngine.error_job won't reload this job, so attempt 2's job.attempt < max_attempts)

This is why we have jobs with `attempt = max_attempts` but `status = retryable/available`!!!

**Comment by sorentwo** [comment]
@dsdshcym Amazing deduction! I'll get a fix in for this before the OSS/Pro release this week 💛

**Comment by sorentwo** [comment]
@dsdshcym This turned out to be as simple as changing to the correct restart strategy. This gist demonstrates the difference: https://gist.github.com/sorentwo/7632ac4c4323ba9e6cf0883b1020c5a8 (tl;dr the task supervisor didn't shut down on producer crash).

The linked issue from Pro will help minimize producer crashes.

**Comment by LiyangW** [comment]
We are having the same error in our service now.  

The environment is:
 * oban: 2.11.3,
 * oban_pro: 0.10.2
 * elixir:1.12
 * pgbouncer:1.15.0 in `transaction` mode
 * postgres: v12
 
Oban config looks like this:
```
config :app, Oban,
  repo: App.Repo,
  engine: Oban.Pro.Queue.SmartEngine,
  plugins: [
    {Oban.Pro.Plugins.DynamicPruner, mode: {:max_age, {1, :minute}}},
    Oban.Plugins.Reindexer,
    Oban.Plugins.Stager,
    Oban.Plugins.Repeater,
    Oban.Pro.Plugins.DynamicLifeline
  ],
  queues: [queue0: 2, queue1: 2, queue2: 2]
```
Note we also use `exAws` in our workers.  The worker config looks like 
```
  use Oban.Worker,
    queue: :queue1,
    max_attempts: 3,
    unique: [
      period: :infinity,
      states: [:available, :scheduled, :executing, :retryable],
      keys: [:username]
    ]
```
Sometimes when our Oban queue used up all the desired attempts of a job, it keeps planning the job afterward.  Then the job would fail immediately with the exact same error message.  Since the same job is constantly re-scheduled, the service loses the ability to consume other new jobs.

I am suspecting that it might have something to do with the PGBouncer in `transaction` mode and `Repeater`, but I'm only guessing.  Could someone please take a look?  Thanks!

**Comment by preciz** [comment]
We have the same problem after upgrading Oban.

    oban: 2.12
    oban_pro: 0.11
    elixir:1.13.3
    postgres: v13

```
          plugins: [
            {
              Oban.Plugins.Cron,
              ...
            },
            {Oban.Plugins.Pruner, [max_age: _1_week = 60 * 60 * 24 * 7]},
            {Oban.Plugins.Gossip, interval: :timer.seconds(5)},
            Oban.Pro.Plugins.Lifeline,
            Oban.Web.Plugins.Stats
          ],
```

We now switched some plugins, but that is the config with which the problem came up.

**Comment by sorentwo** [comment]
@preciz This was a known possibility after the V10 migration.

As there are other instances of this happening, and I can't reproduce it to fix the root cause, I believe a few remediations are in order.

**Comment by preciz** [comment]
It keeps coming back, so I post here the stacktrace in the hope it helps:

```
23:13:29.327 [error] GenServer {Oban.Registry, {Oban..., {:producer, "..."}}} terminating
** (Postgrex.Error) ERROR 23514 (check_violation) new row for relation "oban_jobs" violates check constraint "attempt_range"

    table: oban_jobs
    constraint: attempt_range

Failing row contains (101081361, executing, ..., Octo.Oban, {..., {"{\"at\": \"2022-05-09T23:12:38.197617Z\", \"error\": \"** (Oba..., 4, 3, 2022-05-09 23:12:37.949336, 2022-05-09 23:13:16.290388, 2022-05-09 23:13:29.325926, null, {...4,23230844-9713-4bab-8526-38a4c75c394b}, null, 0, {}, {}, null).
    (ecto_sql 3.8.1) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.8.1) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
    (ecto 3.8.1) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
    (oban_pro 0.11.0) lib/oban/pro/queue/smart_engine.ex:388: Oban.Pro.Queue.SmartEngine.fetch_jobs/2
    (ecto 3.8.1) lib/ecto/multi.ex:723: Ecto.Multi.apply_operation/5
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.8.1) lib/ecto/multi.ex:697: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.8.1) lib/ecto/adapters/sql.ex:1221: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
Last message: :dispatch {erl_level=error domain=otp file=gen_server.erl function=error_info/7 line=949 mfa=:gen_server.error_info/7 module=gen_server pid=<0.2872.0> }
23:13:29.346 [info] Postgrex.Protocol (#PID<0.2806.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.28900.70> exited {erl_level=info application=db_connection domain=elixir file=lib/db_connection/connection.ex function=disconnect/2 line=148 mfa=DBConnection.Connection.disconnect/2 module=DBConnection.Connection pid=<0.2806.0> }
```

**Comment by sorentwo** [comment]
Closing in favor of #652. I've re-opened that issue as this keeps happening.
