### ISSUE TITLE
[Oban Web Doc] Unable to setup multiple dashboards without the `:as` option

### ISSUE THREAD

**Issue by zillou** [sorentwo/oban#534]
### Environment

- Oban Web: 2.7.2
- Phoenix LiveView: 0.16.0

### Current Behavior

The code example about running multiple dashboards listed [here](https://hexdocs.pm/oban/web_installation.html#running-multiple-dashboards) is no longer working with latest phoenix liveview:

```elixir
scope "/" do
  pipe_through :browser

  oban_dashboard "/oban", oban_name: Oban
  oban_dashboard "/oban/admin", oban_name: MyAdmin.Oban
end
```

it will result the following compilation error:

```
Compilation error in file lib/demo_web/router.ex
** (RuntimeError) attempting to redefine live_session :oban_dashboard.
live_session routes must be declared in a single named block.
   (phoenix_live_view 0.16.0) lib/phoenix_live_view/router.ex:238: Phoenix.LiveView.Router.__live_session__/3
    lib/demo_web/router.ex:206: (module)
    (stdlib 3.15.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected Behavior

the `:as` option is mandatory for latest oban web and phoenix liveview.

```diff
  scope "/" do
    pipe_through :browser

-   oban_dashboard "/oban", oban_name: Oban
-   oban_dashboard "/oban/admin", oban_name: MyAdmin.Oban
+   oban_dashboard "/oban", oban_name: Oban, as: :oban_dashboard
+   oban_dashboard "/oban/admin", oban_name: MyAdmin.Oban, as: :admin_oban_dashboard
  end
```

**Comment by sorentwo** [comment]
@zillou Thanks! Fixed.
