### ISSUE TITLE
(Postgrex.Error) ERROR 22007 (invalid_datetime_format) invalid input syntax for type interval: " seconds"

### ISSUE THREAD

**Issue by michallepicki** [sorentwo/oban#567]
### Environment

- Oban Version: oban 2.9.2, oban_pro 0.9.1
- PostgreSQL Version: 11.3
- Elixir & Erlang/OTP Versions: Elixir 1.12.2, Erlang/OTP 24.0.5

### Current Behavior

Given a queue that uses Oban.Pro.Queue.SmartEngine, and a config for that queue similar to:
```
    some_queue_name: [
      global_limit: 3,
      rate_limit: [
        allowed: 30,
        period: {1, :minute},
        partition: [fields: [:args], keys: [:some_arg_key]]
      ]
    ]
```

we're seeing such errors being reported:
```
[error] GenServer {Oban.Registry, {Oban, {:producer, "some_queue_name"}}} terminating 
** (Postgrex.Error) ERROR 22007 (invalid_datetime_format) invalid input syntax for type interval: " seconds" 
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:756: Ecto.Adapters.SQL.raise_sql_call_error/1 
    (ecto_sql 3.7.0) lib/ecto/adapters/sql.ex:689: Ecto.Adapters.SQL.execute/5 
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:219: Ecto.Repo.Queryable.execute/4 
    (ecto 3.7.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3 
    (oban_pro 0.9.1) lib/oban/pro/limiters/rate.ex:62: Oban.Pro.Limiters.Rate.check/2 
    (ecto 3.7.1) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5 
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3 
    (ecto 3.7.1) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5 
Last message: :dispatch 
```

It seems to be crashing 5-10 times in a row for a minute or so, up to a few times per day.

I am not sure but this looks like a bug in rate limiting implementation?

**Comment by sorentwo** [comment]
@michallepicki There was one other report of this, and it turned out they weren't running the `Lifeline` plugin, which left old producer records in the database. The old records have a different `meta` structure, which causes the invalid input syntax issue that you're seeing.

Are you running the lifeline plugin? If not, are you running other instances of the same queue that _aren't_ rate-limited?

**Comment by michallepicki** [comment]
> whether you're running queues with the same name in another node

We do have two nodes running the same codebase, so both of them start the oban supervisor tree with the same config
