### ISSUE TITLE
possible typo in v11 upgrade guide

### ISSUE THREAD

**Issue by ruslandoga** [sorentwo/oban#638]
Should the migrations module name in https://github.com/sorentwo/oban/blob/v2.11.0/guides/upgrading/v2.11.md#run-obanmigrations-for-v11 be `Oban.Migrations` instead of `Oban.Migration`?

```
14:26:28.192 [info]  == Running 20220214112331 App.Repo.Migrations.CreateObanPeers.up/0 forward
** (UndefinedFunctionError) function Oban.Migration.up/1 is undefined (module Oban.Migration is not available)
    Oban.Migration.up([version: 11])
    (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:279: Ecto.Migration.Runner.perform_operation/3
    (stdlib 3.17) timer.erl:166: :timer.tc/1
    (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
    (ecto_sql 3.7.2) lib/ecto/migrator.ex:348: Ecto.Migrator.attempt/8
    (ecto_sql 3.7.2) lib/ecto/migrator.ex:262: anonymous fn/5 in Ecto.Migrator.do_up/5
    (ecto_sql 3.7.2) lib/ecto/migrator.ex:319: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7
    (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.1) lib/db_connection.ex:1531: DBConnection.run_transaction/4
    (ecto_sql 3.7.2) lib/ecto/migrator.ex:337: Ecto.Migrator.run_maybe_in_transaction/5
    (elixir 1.13.1) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.1) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

---

And the compound index migration should probably add `@disable_migration_lock true`:

```
14:28:52.828 [info]  == Running 20220214112544 App.Repo.Migrations.SwapPrimaryObanIndexes.change/0 forward
warning: Migration App.Repo.Migrations.SwapPrimaryObanIndexes has set index `oban_jobs_state_queue_priority_scheduled_at_id_index` on table `oban_jobs` to concurrently but did not disable migration lock. Please set:

    use Ecto.Migration
    @disable_migration_lock true




14:28:52.834 [info]  create index if not exists oban_jobs_state_queue_priority_scheduled_at_id_index
```

**Comment by sorentwo** [comment]
Yes it should. Thanks for the issue and attempted fix. Somebody else got a fix in more quickly.

Closed with #636
