### ISSUE TITLE
Process crashes after upgraded to v2.11

### ISSUE THREAD

**Issue by lauriannala** [sorentwo/oban#640]
### Environment

Upgrading from:
```shell
-      {:oban, "~> 2.10.1"},
-      {:oban_pro, "~> 0.9.4", repo: "oban"},
-      {:oban_web, "~> 2.8.3", repo: "oban"},
+      {:oban, "~> 2.11"},
+      {:oban_pro, "~> 0.10", repo: "oban"},
+      {:oban_web, "~> 2.9", repo: "oban"},
```

### Current Behavior

Can't start application with Oban on the process tree, I'm using dynamic repo and registered name for oban instance.
I just stumbled on this, continuing investigation when I have time.
```
[error] GenServer {Oban.Registry, {<registered_name>, Oban.Midwife}} terminating
** (stop) exited in: GenServer.call(nil, {:listen, [:signal]}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.2) lib/gen_server.ex:1019: GenServer.call/3
    (postgrex 0.16.1) lib/postgrex/simple_connection.ex:212: Postgrex.SimpleConnection.call/3
    (oban 2.11.0) lib/oban/midwife.ex:31: Oban.Midwife.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
State: %Oban.Midwife.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Pro.Queue.SmartEngine, get_dynamic_repo: <dynamic_repo_function>, log: false, name: <name>, node: <node>, notifier: Oban.Notifiers.Po
  stgres, plugins: [Oban.Pro.Plugins.Reprioritizer, Oban.Pro.Plugins.Lifeline, Oban.Plugins.Gossip, Oban.Web.Plugins.Stats, {Oban.Pro.Plugins.DynamicCron, [timezone: "Europe/Helsinki", crontab: <cron_tab>]}, {Oban.Plugins.Pruner, [max_age: 1209600]}, Oban.Plugins.Stager], prefix: <prefix>, queues: <queues>, repo: <repo>, shutdown_grace_period: 15000}}
[error] GenServer {Oban.Registry, {<registered_name>, Oban.Peer}} terminating
** (stop) exited in: GenServer.call(nil, {:listen, [:leader]}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.2) lib/gen_server.ex:1019: GenServer.call/3
    (postgrex 0.16.1) lib/postgrex/simple_connection.ex:212: Postgrex.SimpleConnection.call/3
    (oban 2.11.0) lib/oban/peer.ex:145: Oban.Peer.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
State: %Oban.Peer.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Pro.Queue.SmartEngine, get_dynamic_repo: <dynamic_repo_function>, log: false, name: <name>, node: <node>, notifier: Oban.Notifiers.Postg
  res, plugins: [Oban.Pro.Plugins.Reprioritizer, Oban.Pro.Plugins.Lifeline, Oban.Plugins.Gossip, Oban.Web.Plugins.Stats, {Oban.Pro.Plugins.DynamicCron, [timezone: "Europe/Helsinki", crontab: <crontab]}, {Oban.Plugins.Pruner, [max_age: 1209600]}, Oban.Plugins.Stager], prefix: <prefix>, queues: <queues>, repo: <repo>, shutdown_grace_period: 15000}, interval: 15000
  , leader?: false, leader_boost: 2, name: {:via, Registry, {Oban.Registry, {<registered_name>, Oban.Peer}}}, timer: nil}
[info] start_link: {:error, {:shutdown, {:failed_to_start_child, <supervisor>, {:shutdown, {:failed_to_start_child, <registered_name>, {:shutdown, {:failed_to_start_child, {:plugin, Oban.Web.Plugins.Stats}, {:noproc, {GenServer, :call, [nil, {:listen, [:gossip]},
5000]}}}}}}}}}

```

**Comment by sorentwo** [comment]
The stacktrace indicates that the `<registered_name>` is `nil`, so it can't find the notifier to register. Which environment is this in?

My hunch is that there is a problem in the interaction between `get_dynamic_repo` and extracting config for the Postgres notifier.

**Comment by lauriannala** [comment]
I can reproduce this at least on dev and test environments.

**Comment by lauriannala** [comment]
Removed the dynamic repo and registered name for oban, issue still persistst almost the same:
```
[error] GenServer {Oban.Registry, {Oban, Oban.Midwife}} terminating
** (stop) exited in: GenServer.call(nil, {:listen, [:signal]}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.2) lib/gen_server.ex:1019: GenServer.call/3
    (postgrex 0.16.1) lib/postgrex/simple_connection.ex:212: Postgrex.SimpleConnection.call/3
    (oban 2.11.0) lib/oban/midwife.ex:31: Oban.Midwife.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
State: %Oban.Midwife.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Pro.Queue.SmartEngine, get_dynamic_repo: nil, log: false, name: Oban, node: <node>, notifier: Oban.Notifiers.Postgres, plugins: [Oban.Pro.Plugins.Reprioritizer, Oban.Pro.Plugins.Lifeline, Oban.P
  lugins.Gossip, Oban.Web.Plugins.Stats, {Oban.Pro.Plugins.DynamicCron, [timezone: "Europe/Helsinki", crontab: <crontab>]}, {Oban.Plugins.Pruner, [max_
    age: 1209600]}, Oban.Plugins.Stager], prefix: <prefix>, queues: <queues>, repo: <repo>, shutdown_grace_period: 15000}}
[error] GenServer {Oban.Registry, {Oban, Oban.Peer}} terminating
** (stop) exited in: GenServer.call(nil, {:listen, [:leader]}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.13.2) lib/gen_server.ex:1019: GenServer.call/3
    (postgrex 0.16.1) lib/postgrex/simple_connection.ex:212: Postgrex.SimpleConnection.call/3
    (oban 2.11.0) lib/oban/peer.ex:145: Oban.Peer.handle_continue/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:437: :gen_server.loop/7
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
State: %Oban.Peer.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Pro.Queue.SmartEngine, get_dynamic_repo: nil, log: false, name: Oban, node: <node>, notifier: Oban.Notifiers.Postgres, plugins: [Oban.Pro.Plugins.Reprioritizer, Oban.Pro.Plugins.Lifeline, Oban.Plug
  ins.Gossip, Oban.Web.Plugins.Stats, {Oban.Pro.Plugins.DynamicCron, [timezone: "Europe/Helsinki", crontab: <crontab>]}, {Oban.Plugins.Pruner, [max_age
    : 1209600]}, Oban.Plugins.Stager], prefix: <prefix>, queues: <queues>], repo: <repo>, shutdown_grace_period: 15000}, interval: 15000, leader?: false, leader_boost: 2, name: {:via, Registry, {Oban.Registry, {Oban, Oban.P
eer}}}, timer: nil}
```

**Comment by lauriannala** [comment]
So far I've tried to reproduce this on a simple public repo but to no avail. The environment I have this issue on is pretty much reduced to a simple oban instance with default ecto repo. I think I'll let this be for a while since currently I'm pretty much stuck.

**Comment by sorentwo** [comment]
It looks like the issue is somewhere in the Postgres notifier. Can you confirm that there aren't any crashes if you switch the notifier to `Oban.Notifiers.PG`?

**Comment by lauriannala** [comment]
Ah, it seems that it's asserted, so you can't change it:
```
start_link: {:error, {:shutdown, {:failed_to_start_child, Oban, {:EXIT, {%ArgumentError{message: "expected :notifier to be an Oban.Notifier, got: Oban.Pro.Notifiers.PG"}, [{Oban.Config, :validate_opt!, 1, [
file: 'lib/oban/config.ex', line: 147]}, {Enum, :"-each/2-lists^foreach/1-0-", 2, [file: 'lib/enum.ex', line: 937]}, {Oban.Config, :new, 1, [file: 'lib/oban/config.ex', line: 55]}, {Oban, :start_link, 1, [file: 'l
ib/oban.ex', line: 153]}, {:supervisor, :do_start_child_i, 3, [file: 'supervisor.erl', line: 414]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 400]}, {:supervisor, :"-start_children/2-fun-0-"
, 3, [file: 'supervisor.erl', line: 384]}, {:supervisor, :children_map, 4, [file: 'supervisor.erl', line: 1250]}, {:supervisor, :init_children, 2, [file: 'supervisor.erl', line: 350]}, {:gen_server, :init_it, 2, [
file: 'gen_server.erl', line: 423]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}}}}
```

**Comment by lauriannala** [comment]
The culprit is that I'm setting a name for my repo instance:
```
config :app, Repo,
  name: :default_repo, # <- This bad boy right here.
  ssl_opts: [log_level: :error]
```
So, if I remove the name, the process no longer crashes.

How should I setup Oban so that I can use named default instance of my Repo?

**Comment by sorentwo** [comment]
> Ah, it seems that it's asserted, so you can't change it

It is asserted, but you can change it. The issue there was using the old module name. It should be `Oban.Notifiers.PG`, it isn’t in Pro anymore.

> How should I setup Oban so that I can use named default instance of my Repo?

Thank you for tracking down that issue! The notifier isn’t overriding the name, so the notifier has a name conflict and can’t run. I’ll get a fix out for this.
