### ISSUE TITLE
Oban.Pro Recorded fails if result is other than {:ok | :error, term}

### ISSUE THREAD

**Issue by kaaboaye** [sorentwo/oban#666]
```ex
defmodule RemovalQueue do
  use Oban.Pro.Worker, queue: :some_queue, max_attempts: 3, recorded: true

  @impl true
  def process(%Job{args: %{"something_id" => something_id}}) do
    with %Something{} = something <- Somethings.get_something(something_id) || :discard do
      Somethings.delete_something(something)
    end
  end

  @impl true
  def timeout(_), do: :timer.seconds(5)
end
```

This Queue will fail when `Somethings.get_something(something_id)` returns nil with the following stack trace

```
** (CaseClauseError) no case clause matching: :discard
    (oban_pro 0.10.0) lib/oban/pro/worker.ex:153: anonymous fn/3 in Oban.Pro.Worker.after_process/3
    (elixir 1.12.3) lib/enum.ex:4286: Enumerable.List.reduce/3
    (elixir 1.12.3) lib/enum.ex:2431: Enum.reduce_while/3
    (oban 2.11.0) lib/oban/queue/executor.ex:130: Oban.Queue.Executor.perform/1
    (oban 2.11.0) lib/oban/queue/executor.ex:75: Oban.Queue.Executor.call/1
    (elixir 1.12.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

The job will be retried until the limit is reached which isn't ideal especially when result is defined as.

```ex
  @type result ::
          :ok
          | :discard
          | {:discard, reason :: term()}
          | {:ok, ignored :: term()}
          | {:error, reason :: term()}
          | {:snooze, seconds :: pos_integer()}
```

It fails because `Oban.Pro.Stages.Recorded.after_process/3` will match only `{:ok | :error, term}`.

### Environment

- Oban Version

```ex
[
  "oban": {:hex, :oban, "2.11.2", "250da192bbd59719adeb47abccfb0366df55e0ac571fe2a54cb8e3ebc7a08f2f", [:mix], [{:ecto_sql, "~> 3.6", [hex: :ecto_sql, repo: "hexpm", optional: false]}, {:jason, "~> 1.1", [hex: :jason, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.16", [hex: :postgrex, repo: "hexpm", optional: false]}, {:telemetry, "~> 0.4 or ~> 1.0", [hex: :telemetry, repo: "hexpm", optional: false]}], "hexpm", "9eaf5db3382fc9ace69625844289a1caa5182c74eb58cd6fa02df6ef7a3e9701"},
  "oban_pro": {:hex, :oban_pro, "0.10.2", "95b0a457fe5c7483737b161e151e78a28d80acbdb5841d733c9483807cadc1b0", [:mix], [{:libgraph, "~> 0.13", [hex: :libgraph, repo: "hexpm", optional: true]}, {:oban, "~> 2.11", [hex: :oban, repo: "hexpm", optional: false]}], "oban", "b80492eca8f4e15318f802836633dafd9783686ed9e4d9f7b75738acb963f87e"},
  "oban_web": {:hex, :oban_web, "2.9.1", "9c6ac879e8ef12d1273af54e9b1a6f46ca0ee2ffb03db0c2c889c01d0fd76e00", [:mix], [{:jason, "~> 1.2", [hex: :jason, repo: "hexpm", optional: false]}, {:oban, "~> 2.11", [hex: :oban, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.6", [hex: :phoenix, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 3.1", [hex: :phoenix_html, repo: "hexpm", optional: false]}, {:phoenix_live_view, "~> 0.17.4", [hex: :phoenix_live_view, repo: "hexpm", optional: false]}, {:phoenix_pubsub, "~> 2.0", [hex: :phoenix_pubsub, repo: "hexpm", optional: false]}], "oban", "9e63a3be4a045c7ae9dc79546462778bfdce07f6ab59c143b0e3abf26254959b"}
]
  ```

**Comment by sorentwo** [comment]
This is fixed in v0.10.2: https://getoban.pro/docs/pro/changelog.html#v0-10-2-2022-03-03
