### ISSUE TITLE
Version doesn't seem to be respected in migration on CI

### ISSUE THREAD

**Issue by jc00ke** [sorentwo/oban#69]
I have 2 migrations:

```elixir
# 20190530181624_add_oban_jobs_table.exs
defmodule MyApp.Repo.Migrations.AddObanJobsTable do
  use Ecto.Migration

  defdelegate up, to: Oban.Migrations
  defdelegate down, to: Oban.Migrations
end

# 20190917224931_upgrade_oban_to_v3.exs
defmodule MyApp.Repo.Migrations.UpgradeObanToV3 do
  use Ecto.Migration

  def up do
    Oban.Migrations.up(version: 3)
  end

  def down do
    Oban.Migrations.down(version: 2)
  end
end
```

This last migration worked fine with my `staging` database, but when building fresh for CI, I run into the following error:

```
.
.
.
.
.
23:21:39.543 [info]  == Running 20190530181624 MyApp.Repo.Migrations.AddObanJobsTable.up/0 forward

23:21:39.550 [info]  execute "CREATE SCHEMA IF NOT EXISTS public"

23:21:39.550 [info]  schema "public" already exists, skipping

23:21:39.550 [info]  execute "DO $$\nBEGIN\nIF NOT EXISTS (SELECT 1 FROM pg_type\n               WHERE typname = 'oban_job_state'\n                 AND typnamespace = 'public'::regnamespace::oid) THEN\n    CREATE TYPE public.oban_job_state AS ENUM (\n      'available',\n      'scheduled',\n      'executing',\n      'retryable',\n      'completed',\n      'discarded'\n    );\n  END IF;\nEND$$;\n"

23:21:39.552 [info]  create table if not exists public.oban_jobs

23:21:39.556 [info]  create index if not exists public.oban_jobs_queue_index

23:21:39.557 [info]  create index if not exists public.oban_jobs_state_index

23:21:39.559 [info]  create index if not exists public.oban_jobs_scheduled_at_index

23:21:39.560 [info]  execute "CREATE OR REPLACE FUNCTION public.oban_jobs_notify() RETURNS trigger AS $$\nDECLARE\n  channel text;\n  notice json;\nBEGIN\n  IF (TG_OP = 'INSERT') THEN\n    channel = 'public.oban_insert';\n    notice = json_build_object('queue', NEW.queue, 'state', NEW.state);\n\n    -- No point triggering for a job that isn't scheduled to run now\n    IF NEW.scheduled_at IS NOT NULL AND NEW.scheduled_at > now() AT TIME ZONE 'utc' THEN\n      RETURN null;\n    END IF;\n  ELSE\n    channel = 'public.oban_update';\n    notice = json_build_object('queue', NEW.queue, 'new_state', NEW.state, 'old_state', OLD.state);\n  END IF;\n\n  PERFORM pg_notify(channel, notice::text);\n\n  RETURN NULL;\nEND;\n$$ LANGUAGE plpgsql;\n"

23:21:39.561 [info]  execute "DROP TRIGGER IF EXISTS oban_notify ON public.oban_jobs"

23:21:39.561 [info]  trigger "oban_notify" for relation "public.oban_jobs" does not exist, skipping

23:21:39.561 [info]  execute "CREATE TRIGGER oban_notify\nAFTER INSERT OR UPDATE OF state ON public.oban_jobs\nFOR EACH ROW EXECUTE PROCEDURE public.oban_jobs_notify();\n"

23:21:39.562 [info]  execute "COMMENT ON TABLE public.oban_jobs IS '1'"

23:21:39.563 [info]  drop index if exists public.oban_jobs_scheduled_at_index

23:21:39.563 [info]  create index public.oban_jobs_scheduled_at_index

23:21:39.564 [info]  create check constraint worker_length on table public.oban_jobs

23:21:39.565 [info]  create check constraint queue_length on table public.oban_jobs

23:21:39.566 [info]  execute "CREATE OR REPLACE FUNCTION public.oban_wrap_id(value bigint) RETURNS int AS $$\nBEGIN\n  RETURN (CASE WHEN value > 2147483647 THEN mod(value, 2147483647) ELSE value END)::int;\nEND;\n$$ LANGUAGE plpgsql IMMUTABLE;\n"

23:21:39.566 [info]  execute "COMMENT ON TABLE public.oban_jobs IS '2'"

23:21:39.567 [info]  alter table public.oban_jobs

23:21:39.567 [info]  create table if not exists public.oban_beats

23:21:39.569 [info]  create index if not exists public.oban_beats_inserted_at_index

23:21:39.571 [info]  execute "COMMENT ON TABLE public.oban_jobs IS '3'"

23:21:39.571 [info]  execute "DROP FUNCTION IF EXISTS public.oban_wrap_id(value bigint)"

23:21:39.572 [info]  execute "COMMENT ON TABLE public.oban_jobs IS '4'"

23:21:39.572 [info]  == Migrated 20190530181624 in 0.0s

.
.
.
.
.

23:21:39.687 [info]  == Running 20190917224931 MyApp.Repo.Migrations.UpgradeObanToV3.up/0 forward

23:21:39.688 [info]  execute "DROP FUNCTION IF EXISTS public.oban_wrap_id(value bigint)"

23:21:39.688 [info]  function public.oban_wrap_id(pg_catalog.int8) does not exist, skipping

23:21:39.688 [info]  execute "COMMENT ON TABLE public.oban_jobs IS '4'"

23:21:39.689 [info]  alter table public.oban_jobs

** (Postgrex.Error) ERROR 42701 (duplicate_column) column "attempted_by" of relation "oban_jobs" already exists

    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1

    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2

    (ecto_sql) lib/ecto/adapters/sql.ex:716: Ecto.Adapters.SQL.execute_ddl/4

    (ecto_sql) lib/ecto/migration/runner.ex:338: Ecto.Migration.Runner.log_and_execute_ddl/3

    (ecto_sql) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0

    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3

    (ecto_sql) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0

    (stdlib) timer.erl:166: :timer.tc/1
```

It looks like Oban got fully migrated (we're not live on production, so a little bit of downtime is acceptable) but unless I remove a migration, I'm not sure how to keep both CI and staging/prod happy.

**Comment by sorentwo** [comment]
Great catch. Man, the migration stuff has been my nemesis. I threw property tests at it this time and found a few edge cases. Thanks for the report!

**Comment by jc00ke** [comment]
Thanks for the quick fix! Do you have plans to release this as 0.8.2 or should I run off `master` for a minute?

**Comment by sorentwo** [comment]
@jc00ke I'll do a `0.8.2` release, there are a few fixes that are worth packaging up.

**Comment by sorentwo** [comment]
On second thought, I'm going to get the `insert_all` support in and release `0.9.0` this week. Please run off master, if you wouldn't mind.

**Comment by jc00ke** [comment]
Will do. I just ran into this issue when trying to migrate my test db.
