### ISSUE TITLE
Oban crashes when Ecto logging is disabled

### ISSUE THREAD

**Issue by lucasmazza** [sorentwo/oban#73]
I've noticed this on our team app and I managed to replicate it with a standalone Phoenix app. Disabling a Repo `log` option with:

```diff
diff --git a/config/dev.exs b/config/dev.exs
index 108ccc1..59d9332 100644
--- a/config/dev.exs
+++ b/config/dev.exs
@@ -5,6 +5,7 @@ config :testapp, Testapp.Repo,
   username: "lucas",
   database: "testapp_dev",
   hostname: "localhost",
+  log: false,
   show_sensitive_data_on_connection_error: true,
   pool_size: 10
 ```

Makes Oban crash with the following:

```
[error] an exception was raised logging %DBConnection.LogEntry{call: :prepare_execute, connection_time: 3421000, decode_time: 1568000, params: ["available", ~U[2019-09-25 18:30:55.041959Z], "default"], pool_time: 534252000, query: %Postgrex.Query{cache: :reference, columns: nil, name: "ecto_3205", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "UPDATE \"public\".\"oban_jobs\" AS o0 SET \"state\" = $1 FROM (SELECT o0.\"id\" AS \"id\" FROM \"public\".\"oban_jobs\" AS o0 LEFT OUTER JOIN \"public\".\"oban_beats\" AS o1 ON (o0.\"attempted_by\" = ARRAY[o1.\"node\",o1.\"queue\",o1.\"nonce\"]) AND (o1.\"inserted_at\" > $2) WHERE ((o0.\"state\" = 'executing') AND (o0.\"queue\" = $3)) AND (o1.\"node\" IS NULL)) AS s1 WHERE (o0.\"id\" = s1.\"id\")", types: nil}, result: {:ok, %Postgrex.Query{cache: :reference, columns: nil, name: "ecto_3205", param_formats: [:binary, :binary, :binary], param_oids: [16916, 1114, 25], param_types: [Postgrex.Extensions.Raw, Postgrex.Extensions.Timestamp, Postgrex.Extensions.Raw], ref: #Reference<0.701822816.1820852225.69693>, result_formats: [], result_oids: nil, result_types: nil, statement: "UPDATE \"public\".\"oban_jobs\" AS o0 SET \"state\" = $1 FROM (SELECT o0.\"id\" AS \"id\" FROM \"public\".\"oban_jobs\" AS o0 LEFT OUTER JOIN \"public\".\"oban_beats\" AS o1 ON (o0.\"attempted_by\" = ARRAY[o1.\"node\",o1.\"queue\",o1.\"nonce\"]) AND (o1.\"inserted_at\" > $2) WHERE ((o0.\"state\" = 'executing') AND (o0.\"queue\" = $3)) AND (o1.\"node\" IS NULL)) AS s1 WHERE (o0.\"id\" = s1.\"id\")", types: {Postgrex.DefaultTypes, #Reference<0.701822816.1820983299.68770>}}, %Postgrex.Result{columns: nil, command: :update, connection_id: 73888, messages: [], num_rows: 0, rows: nil}}}: ** (FunctionClauseError) no function clause matching in Logger.__should_log__/1
    (logger) lib/logger.ex:668: Logger.__should_log__(false)
    (ecto_sql) lib/ecto/adapters/sql.ex:810: Ecto.Adapters.SQL.log/4
    (db_connection) lib/db_connection.ex:1377: DBConnection.log/5
    (ecto_sql) lib/ecto/adapters/sql.ex:570: Ecto.Adapters.SQL.execute!/4
    (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (oban) lib/oban/queue/producer.ex:153: Oban.Queue.Producer.rescue_orphans/1
    (oban) lib/oban/queue/producer.ex:83: Oban.Queue.Producer.handle_continue/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:388: :gen_server.loop/7
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Removing `Oban` from the supervision tree and/or skipping the `log: false` option fixes the issue, and the web server still work as expected even when `log` is `false`.

**Comment by sorentwo** [comment]
Are you able to replicate this with a simple Ecto query where you specify `log: false`? Oban isn't doing anything fancy with the `verbose` value, it is passing it through as `log: true` or `log: false` for each query.

**Comment by lucasmazza** [comment]
@sorentwo we can replicate this with:

```elixir
Ecto.Adapters.SQL.query!(Testapp.Repo, "SELECT 1 AS one", [], log: true)
```

The `log: true` matches the defaults from `Oban.Config`

**Comment by lucasmazza** [comment]
On a side one, if we supply a log level, instead of `true`, the query is logged as expected, overriding the repo config:

```elixir
Keyword.get(Testapp.Repo.config(), :log)
# false
Ecto.Adapters.SQL.query!(Testapp.Repo, "SELECT 1 AS one", [], log: :info)
# [info] QUERY OK db=0.4ms queue=0.7ms
# SELECT 1 AS one []
```

The documentation on [`Ecto.Repo`](https://hexdocs.pm/ecto/Ecto.Repo.html) has the following to say about the `:log` option:

```
the log level used when logging the query with Elixir's Logger. If false, disables 
logging for that repository. Defaults to :debug
```

Is never explicitly said to support `true` (like `verbose` does here), so maybe oban should follow the same semantics of "log_level or `false`" instead of being either "`true` and `false`"?

**Comment by sorentwo** [comment]
@lucasmazza Thanks gain. Pushed a patch that prevents this from happening, and encourages a more sensible default.

**Comment by lucasmazza** [comment]
@sorentwo thanks for the always fast and focused patches ❤️
