### ISSUE TITLE
Problem with timeout when scheduling unique jobs

### ISSUE THREAD

**Issue by isavita** [sorentwo/oban#734]
### Environment

- Oban Version
**2.12.1**
- PostgreSQL Version
**PostgreSQL 13.5** 
- Elixir & Erlang/OTP Versions (`elixir --version`)
**Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]**
**Elixir 1.12.3 (compiled with Erlang/OTP 24)**

### Current Behavior
I am running a task separate from my main application in which I am schedule emails using **Oban** with the unique feature (no **Oban.insert_all**. My code looks something as
```elixir
defmodule MyService.Task do
  def call do 
    Application.load(:my_service)

    {:ok, _, _} = Ecto.Migrator.with_repo(MyService.Repo, fn repo ->
       start_oben(repo)
       
       Repo.transaction(fn ->
          ...
          job = SendEmailWorker.new(data) 
          Oban.insert(job)
       end)
    end)
  end
  
  defp start_oben(repo) do
    Application.ensure_all_started(:oban)

     :my_service
     |> Application.fetch_env!(Oban)
     |> Keyword.put(:repo, repo)
     |> Oban.start_link()
  end
end
```
When I schedule a few jobs all works perfect! But when I try to schedule ~6k.
I am getting timeout error
```shell
Postgrex.Protocol (#PID<0.274.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.165.0> timed out because it queued and checked out the 
 main ** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout        
  main     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1      
  main     (ecto 3.8.4) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4                                                              
  main     (ecto 3.8.4) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4       
  main     (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4 
  main     (db_connection 2.4.2) lib/db_connection.ex:865: DBConnection.transaction/3          
    (oban 2.12.1) lib/oban/queue/basic_engine.ex:53: Oban.Queue.BasicEngine.insert_job/2    
      main     (oban 2.12.1) lib/oban/queue/engine.ex:234: anonymous fn/3 in Oban.Queue.Engine.with_span/4      
        (telemetry 1.1.0) /app/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3
```
I changed my Ecto timeout config to `timeout 20 mins`.
```elixir
config :my_service, MyService.Repo,
  url: "....",
  pool_size: 10,
  timeout: 1_200_000
```
 It did not help. I am not sure what can be the cause of the problem.
 Also it seems like the `timeout: 1_200_000` is ignored because I am still getting error after 15s.
 Is it possible because of the Oban.insert(job) is part of big transaction?
### Expected Behavior
I expect to schedule ~7k jobs for less than 20 minutes.
Is there some Oban's config that I can configure the `timeout: 1_200_000`?

**Comment by isavita** [comment]
It was problem with my argo config and scheduling the `setting up the timeout: 1_200_000` worked.
I am closing the issue.
