### ISSUE TITLE
Failing to apply migrations on first setup

### ISSUE THREAD

**Issue by jarmo** [sorentwo/oban#740]
### Environment

- Oban Version
2.21.1

- PostgreSQL Version
9.5.24

- Elixir & Erlang/OTP Versions (`elixir --version`)
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1]
Elixir 1.13.1 (compiled with Erlang/OTP 24)

### Current Behavior

I've tried to add Oban to my project and created a migration like this:

```
defmodule MyApp.Repo.Migrations.AddObanJobsTable do
  use Ecto.Migration

  def up do
    Oban.Migrations.up(version: 11)
  end

  # We specify `version: 1` in `down`, ensuring that we'll roll all the way back down if
  # necessary, regardless of which version we've migrated `up` to.
  def down do
    Oban.Migrations.down(version: 1)
  end
end
```

Running migrations will fail:

```
21:07:12.606 [info]  execute "DO $$\nBEGIN\nIF NOT EXISTS (SELECT 1 FROM pg_type\n               WHERE typname = 'oban_job_state'\n                 AND typnamespace = 'public'::regnamespace::oid) THEN\n    CREATE TYPE public.oban_job_state AS ENUM (\n      'available',\n      'scheduled',\n      'executing',\n      'retryable',\n      'completed',\n      'discarded'\n    );\n  END IF;\nEND$$;\n"
21:07:12.609 [info]  create table if not exists public.oban_jobs
21:07:12.620 [info]  create index if not exists public.oban_jobs_queue_index
21:07:12.623 [info]  create index if not exists public.oban_jobs_state_index
21:07:12.626 [info]  create index if not exists public.oban_jobs_scheduled_at_index
21:07:12.629 [info]  execute "CREATE OR REPLACE FUNCTION public.oban_jobs_notify() RETURNS trigger AS $$\nDECLARE\n  channel text;\n  notice json;\nBEGIN\n  IF (TG_OP = 'INSERT') THEN\n    channel = 'public.oban_insert';\n    notice = json_build_object('queue', NEW.queue, 'state', NEW.state);\n\n    -- No point triggering for a job that isn't scheduled to run now\n    IF NEW.scheduled_at IS NOT NULL AND NEW.scheduled_at > now() AT TIME ZONE 'utc' THEN\n      RETURN null;\n    END IF;\n  ELSE\n    channel = 'public.oban_update';\n    notice = json_build_object('queue', NEW.queue, 'new_state', NEW.state, 'old_state', OLD.state);\n  END IF;\n\n  PERFORM pg_notify(channel, notice::text);\n\n  RETURN NULL;\nEND;\n$$ LANGUAGE plpgsql;\n"
21:07:12.630 [info]  execute "DROP TRIGGER IF EXISTS oban_notify ON public.oban_jobs"
21:07:12.630 [info]  trigger "oban_notify" for relation "public.oban_jobs" does not exist, skipping
21:07:12.630 [info]  execute "CREATE TRIGGER oban_notify\nAFTER INSERT OR UPDATE OF state ON public.oban_jobs\nFOR EACH ROW EXECUTE PROCEDURE public.oban_jobs_notify();\n"
21:07:12.630 [info]  drop index if exists public.oban_jobs_scheduled_at_index
21:07:12.631 [info]  create index public.oban_jobs_scheduled_at_index
21:07:12.634 [info]  create check constraint worker_length on table public.oban_jobs
21:07:12.635 [info]  create check constraint queue_length on table public.oban_jobs
21:07:12.636 [info]  execute "CREATE OR REPLACE FUNCTION public.oban_wrap_id(value bigint) RETURNS int AS $$\nBEGIN\n  RETURN (CASE WHEN value > 2147483647 THEN mod(value, 2147483647) ELSE value END)::int;\nEND;\n$$ LANGUAGE plpgsql IMMUTABLE;\n"
21:07:12.636 [info]  alter table public.oban_jobs
** (Postgrex.Error) ERROR 42601 (syntax_error) syntax error at or near "NOT"
    query: ALTER TABLE "public"."oban_jobs" ADD COLUMN IF NOT EXISTS "attempted_by" text[]
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:352: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    (ecto_sql 3.8.3) lib/ecto/migration/runner.ex:289: Ecto.Migration.Runner.perform_operation/3
```

**Comment by sorentwo** [comment]
Your Postgres version isn’t current enough. Oban requires 10.0+ officially, 9.6 unofficially.

See the requirements section of the readme: https://hexdocs.pm/oban/Oban.html#module-requirements
