### ISSUE TITLE
Insert multiple jobs error when elixir version less than 1.13

### ISSUE THREAD

**Issue by oo6** [sorentwo/oban#747]
### Environment

- Oban Version
  - oban: 2.13.0
  - oban_pro: 0.12.1
- PostgreSQL Version
  14.4
- Elixir & Erlang/OTP Versions (`elixir --version`)
  - Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]
  - Elixir 1.12.3 (compiled with Erlang/OTP 24)

### Current Behavior

When I run code:
```elixir
# config :my_app, Oban,
#  engine: Oban.Pro.Queue.SmartEngine,
#  ...

1..100
|> Enum.map(&MyApp.Worker.new(%{id: &1}))
|> Oban.insert_all()
```
Got error:
```
** (UndefinedFunctionError) function Map.reject/2 is undefined or private
    (elixir 1.12.3) Map.reject(%{args: %{id: 1}, attempt: 0, errors: [], max_attempts: 20, meta: %{}, priority: 0, queue: "default", state: "available", tags: [], worker: "MyApp.Worker"}, #Function<48.67355288/1 in Oban.Pro.Queue.SmartEngine.insert_entries/2>)
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/2-lists^foldl/2-0-"/3
    (oban_pro 0.12.1) lib/oban/pro/queue/smart_engine.ex:765: Oban.Pro.Queue.SmartEngine.insert_entries/2
    (ecto 3.8.4) lib/ecto/multi.ex:794: Ecto.Multi.apply_operation/5
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.8.4) lib/ecto/multi.ex:768: anonymous fn/5 in Ecto.Multi.apply_operations/5
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
    (ecto 3.8.4) lib/ecto/repo/transaction.ex:18: Ecto.Repo.Transaction.transaction/4
    (oban_pro 0.12.1) lib/oban/pro/queue/smart_engine.ex:648: Oban.Pro.Queue.SmartEngine.transaction/2
    (oban_pro 0.12.1) lib/oban/pro/queue/smart_engine.ex:361: anonymous fn/2 in Oban.Pro.Queue.SmartEngine.insert_all_jobs/3
```
Because elixir add `Map.reject/2` since 1.13.

### Expected Behavior

I found `elixir: "~> 1.11"` in `oban_pro/mix.exs`, So I expected insert multiple jobs success.

**Comment by sorentwo** [comment]
@oo6 Fixed! Look for a patch out soon (today or tomorrow).
