### ISSUE TITLE
Process crash after upgrade to v2.13

### ISSUE THREAD

**Issue by onomated** [sorentwo/oban#812]
### Precheck
I see reports of similar errors https://github.com/sorentwo/oban/issues/640 and https://github.com/sorentwo/oban/issues/753.  Both these issues are addressed in prior versions of Oban

### Environment
Upgraded from:

```
-  "oban": "2.10.1"
-  "oban_pro": "0.9.4"
-  "oban_web": "2.8.3"
+  "oban": "2.13.6"
+  "oban_pro": "0.12.9"
+  "oban_web": "2.9.6"
```

Umbrella with applications `MyApp` and `MyAppWeb` with the following config:
```
config :my_app, Oban,
  repo: MyApp.Repo,
  engine: Oban.Pro.Queue.SmartEngine,
  plugins: [
    Oban.Pro.Plugins.Lifeline,
    # https://hexdocs.pm/oban/Oban.Plugins.Gossip.html
    {Oban.Plugins.Gossip, interval: :timer.seconds(10)},
    # https://hexdocs.pm/oban/dynamic_pruner.html
    {
      Oban.Pro.Plugins.DynamicPruner,
      # Keep job data for 5mins and delete up to 20k jobs at a time
      # For the migrate batcher delete every half minutes to avoid uniqueness conflicts with 1min chron
      mode: {:max_age, {5, :minute}},
      limit: 25_000,
      queue_overrides: [migration: {:max_age, {30, :second}}]
    },
    # https://hexdocs.pm/oban/batch.html
    Oban.Pro.Plugins.BatchManager,
    # https://hexdocs.pm/oban/dynamic_cron.html#content
    {
      Oban.Pro.Plugins.DynamicCron,
      timezone: "America/Chicago",
      crontab: [
        {
          "* * * * *",
          MyApp.Workers.Migrate,
          name: "legacy_migrate", max_attempts: 1
        }
      ]
    }
  ],
  queues: [default: 10, migration: 20]

# Oban plugins in web app includes web plugins only
config :my_app_web, Oban,
  repo: MyApp.Repo,
  name: MyApp.Oban,
  plugins: [
    Oban.Web.Plugins.Stats
  ]
```

### Current Behavior

Process crash at on running tests with the following message:

```
13:14:05.818 [error] Postgrex.Protocol (#PID<0.2775.0>) disconnected: ** (DBConnection.ConnectionError) #PID<0.95.0> checked in the connection owned by #PID<0.2882.0>

#PID<0.95.0> triggered the checkin at location:

    (kernel 8.5.1) code_server.erl:139: :code_server.call/1
    (elixir 1.14.2) src/elixir_compiler.erl:67: :elixir_compiler.dispatch/4
    (elixir 1.14.2) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
    (elixir 1.14.2) src/elixir_compiler.erl:39: :elixir_compiler.eval_or_compile/3
    (elixir 1.14.2) src/elixir_lexical.erl:15: :elixir_lexical.run/3
    (elixir 1.14.2) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
    (elixir 1.14.2) lib/module/parallel_checker.ex:107: Module.ParallelChecker.verify/1
    (elixir 1.14.2) lib/code.ex:1260: Code.require_file/2


Client #PID<0.2882.0> is still using a connection from owner at location:

    (kernel 8.5.1) code_server.erl:139: :code_server.call/1
    (kernel 8.5.1) error_handler.erl:40: :error_handler.undefined_function/3
    (stdlib 4.1.1) lists.erl:1442: :lists.foreach_1/2
    (ecto_sql 3.9.1) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.log/4
    (db_connection 2.4.3) lib/db_connection.ex:1559: DBConnection.log/5
    (db_connection 2.4.3) lib/db_connection.ex:945: DBConnection.transaction/3

The connection itself was checked out by #PID<0.2882.0> at location:

    (oban 2.13.6) lib/oban/peers/postgres.ex:90: Oban.Peers.Postgres.handle_info/2


13:14:05.851 [error] GenServer {Oban.Registry, {ModuleWeb.Oban, Oban.Peer}} terminating
** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout
    (ecto_sql 3.9.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.9.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (oban 2.13.6) lib/oban/peers/postgres.ex:145: Oban.Peers.Postgres.delete_expired_peers/1
    (oban 2.13.6) lib/oban/peers/postgres.ex:92: anonymous fn/1 in Oban.Peers.Postgres.handle_info/2
    (ecto_sql 3.9.1) lib/ecto/adapters/sql.ex:1202: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.3) lib/db_connection.ex:1611: DBConnection.run_transaction/4
    (oban 2.13.6) lib/oban/peers/postgres.ex:90: Oban.Peers.Postgres.handle_info/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
Last message: {:continue, :start}
State: %Oban.Peers.Postgres.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, log: false, name: MyAppWeb.Oban, node: "Machine-Name", notifier: Oban.Notifiers.Postgres, peer: Oban.Peers.Postgres, plugins: [Oban.Web.Plugins.Stats, Oban.Plugins.Stager], prefix: "public", queues: [], repo: MyApp.Repo, shutdown_grace_period: 15000, testing: :disabled}, name: {:via, Registry, {Oban.Registry, {MyAppWeb.Oban, Oban.Peer}}}, timer: nil, interval: 30000, leader?: false, leader_boost: 2}
13:14:05.870 [error] GenServer {Oban.Registry, {MyAppWeb.Oban, Oban.Peer}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.2896.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection 2.4.3) lib/db_connection.ex:953: DBConnection.transaction/3
    (oban 2.13.6) lib/oban/peers/postgres.ex:90: Oban.Peers.Postgres.handle_info/2
    (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1.1) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start}
State: %Oban.Peers.Postgres.State{conf: %Oban.Config{dispatch_cooldown: 5, engine: Oban.Engines.Basic, get_dynamic_repo: nil, log: false, name: MyAppWeb.Oban, node: "Machine-Name", notifier: Oban.Notifiers.Postgres, peer: Oban.Peers.Postgres, plugins: [Oban.Web.Plugins.Stats, Oban.Plugins.Stager], prefix: "public", queues: [], repo: MyApp.Repo, shutdown_grace_period: 15000, testing: :disabled}, name: {:via, Registry, {Oban.Registry, {MyAppWeb.Oban, Oban.Peer}}}, timer: nil, interval: 30000, leader?: false, leader_boost: 2}
13:14:05.870 [error] GenServer {Oban.Registry, {MyAppWeb.Oban, Oban.Peer}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.2897.0>.
```

**Comment by dvic** [comment]
Did you configure the `testing` option? see upgrade guide of 2.12: https://hexdocs.pm/oban/v2-12.html

**Comment by onomated** [comment]
Yes I did.  Here's my config.  Same error with both `:manual` and `:inline`:

```
config :my_app, Oban, crontab: false, testing: :manual
```

**Comment by onomated** [comment]
Ah, just realized I have to configure the testing option on both apps.  This works!:

```
config :my_app, Oban, crontab: false, testing: :manual
config :my_app_web, Oban, crontab: false, testing: :manual
```

Thanks @dvic !
