### ISSUE TITLE
Pro: insert with replace is broken on oban_pro 0.13 on inserting a non conflicting row

### ISSUE THREAD

**Issue by DarkArchonMind** [sorentwo/oban#834]
### Environment

- Oban Version: 2.14.1, pro 0.13.0, web 0.9.0
- PostgreSQL Version: 12.2
- Elixir & Erlang/OTP Versions (`elixir --version`): elixir 1.12.2, erlang otp 24 (Erts-12.0.3)

### Current Behavior

Make a worker that checks uniqueness against args:

```
  use Oban.Pro.Worker,
    queue: :queue1,
    unique: [
      period: :infinity,
      fields: [:args],
      states: [:available, :scheduled, :executing]
    ]
```

Then on a fresh environment (e.g. a test case), try to insert a new job with a replace of `:scheduled_at`

```
new_job = NewJob.new(
    %{data: "abcd"},
          scheduled_at: time1,
          meta: %{track: "queue1"},
          replace: [:scheduled_at]
        )

Oban.insert(new_job)
```

### Expected Behavior

Expected: It inserts correctly since there's no existing conflicting job

Actual: we get a crash in smartengine

```
** (MatchError) no match of right hand side value: nil
     code: Oban.insert(new_job)
     stacktrace:
       (oban_pro 0.13.0) lib/oban/pro/queue/smart_engine.ex:883: anonymous fn/3 in Oban.Pro.Queue.SmartEngine.apply_replacements/2
       (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (oban_pro 0.13.0) lib/oban/pro/queue/smart_engine.ex:877: Oban.Pro.Queue.SmartEngine.apply_replacements/2
       (ecto 3.7.2) lib/ecto/multi.ex:716: Ecto.Multi.apply_operation/5
       (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto 3.7.2) lib/ecto/multi.ex:690: anonymous fn/5 in Ecto.Multi.apply_operations/5
       (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.4.3) lib/db_connection.ex:914: DBConnection.transaction/3
       (ecto 3.7.2) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
       (oban_pro 0.13.0) lib/oban/pro/queue/smart_engine.ex:728: Oban.Pro.Queue.SmartEngine.transaction/3
       (oban_pro 0.13.0) lib/oban/pro/queue/smart_engine.ex:404: anonymous fn/3 in Oban.Pro.Queue.SmartEngine.inner_insert_all/3
       (elixir 1.12.2) lib/enum.ex:3894: Enum.flat_map_list/2
       (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.4.3) lib/db_connection.ex:1611: DBConnection.run_transaction/4
       (oban_pro 0.13.0) lib/oban/pro/queue/smart_engine.ex:370: Oban.Pro.Queue.SmartEngine.insert_all_jobs/3
       (oban_pro 0.13.0) lib/oban/pro/queue/smart_engine.ex:352: Oban.Pro.Queue.SmartEngine.insert_job/3
       (oban 2.14.1) lib/oban/engine.ex:170: anonymous fn/4 in Oban.Engine.insert_job/3
       (oban 2.14.1) lib/oban/engine.ex:282: anonymous fn/3 in Oban.Engine.with_span/4
```

A quick look at the code seems to suggest it's expecting to find dupe info for the entry, but doesn't find any (since there is none), and then crashing on the match

Downgrading to oban_pro 0.12.10 and oban 2.13.6 seems to work (we updated today from oban_pro 0.9/oban 2.10 since we were running into issues with timeouts of bulk inserts done one at a time and wanted to use the new insert_all with uniqueness)

**Comment by sorentwo** [comment]
@DarkArchonMind Thanks for the report! The fix will be out in v0.13.1 soon.
