### ISSUE TITLE
GenServer {Oban.Registry, {Oban, Oban.Stager}} terminating when running tests

### ISSUE THREAD

**Issue by jaimeiniesta** [sorentwo/oban#853]
### Environment

- Oban v2.14.2, Oban.Web v2.9.6, Oban.Pro v0.13.1 
- PostgreSQL 14
- Erlang/OTP 23 [erts-11.2.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
- Elixir 1.13.4 (compiled with Erlang/OTP 23)

### Current Behavior

Since I've upgraded to the latest versions, I get this when I run `mix test`

```
13:16:34.599 [error] GenServer {Oban.Registry, {Oban, Oban.Stager}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.1018.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection 2.4.3) lib/db_connection.ex:953: DBConnection.transaction/3
    (oban 2.14.2) lib/oban/stager.ex:86: anonymous fn/2 in Oban.Stager.handle_info/2
    (telemetry 1.2.1) /Users/jaime/code/myapp/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (oban 2.14.2) lib/oban/stager.ex:85: Oban.Stager.handle_info/2
    (stdlib 3.14.2.2) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.2.2) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :stage
```

### Expected Behavior

No crash :)

**Comment by sorentwo** [comment]
That can happen with the old `plugins: false, queues: false` config for tests.

As of v2.12, the correct way to configure for testing is with `testing: :manual` or `testing: :inline` which was part of the [v2.12 upgrade guide](https://hexdocs.pm/oban/v2-12.html#modify-configuration-for-testing). That option will disable queues, plugins, peering, etc. all while validating the complete config.

**Comment by jaimeiniesta** [comment]
Ah, I see! I missed that part, my fault. Changing that fixed the tests, thanks!
